<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\DCInstallation;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

class DCInstallationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Disable foreign key checks for faster seeding (database-agnostic)
        $this->disableForeignKeyChecks();

        // Truncate existing data
        DCInstallation::truncate();

        // Enable foreign key checks
        $this->enableForeignKeyChecks();

        // Get all installation data
        $allData = array_merge(
            $this->getDataBatch1(),
            $this->getDataBatch2(),
            $this->getDataBatch3()
            // Add more batches as needed for all 624 records
        );

        // Insert data in chunks for better performance
        $chunkSize = 50;
        $chunks = array_chunk($allData, $chunkSize);

        foreach ($chunks as $chunk) {
            foreach ($chunk as $installation) {
                try {
                    // Add timestamps
                    $installation['created_at'] = Carbon::now();
                    $installation['updated_at'] = Carbon::now();

                    // Handle null values for NOT NULL fields
                    $installation = $this->handleNotNullConstraints($installation);

                    DCInstallation::create($installation);
                } catch (\Exception $e) {
                    // Log error and continue with next record
                    Log::error("Failed to seed DC Installation: " . $e->getMessage(), [
                        'sr_no' => $installation['sr_no'] ?? 'unknown'
                    ]);
                }
            }
        }

        $this->command->info('DCInstallation seeder completed successfully!');
        $this->command->info('Total records seeded: ' . count($allData));
    }

    /**
     * Data Batch 1 - Records 1-10
     */
    private function getDataBatch1()
    {
        return [
            [
                'sr_no' => 'DC-0001-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Deputy Director, Land Records, Amravati Region, Amravati New Taluka Administrative Building "In front of the Cultural Building", Morshi Road, Amravati 444 602',
                'district' => 'Amravati',
                'tahsil' => 'Amravati',
                'pin_code' => '444602',
                'receiver_name' => 'Ms. Sunayana Telgote',
                'contact_no' => '9822366317',
                'dc_ir_no' => '001',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390501',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008HD',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008HD',
                'hp_keyboard_serial' => 'BKTCF0CCPKPNZY',
                'hp_mouse_serial' => 'FKTFR0AJPKPMT4',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '1-AM-DDLR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0002-IN',
                'region_division' => 'Amravati',
                'location_address' => 'District Superintendent, Land Records, 444001, Akola District Collector Office Premises, Akola',
                'district' => 'Akola',
                'tahsil' => 'Akola',
                'pin_code' => '444001',
                'receiver_name' => 'Mr. Pramod Rangari',
                'contact_no' => '9970176923',
                'dc_ir_no' => '002',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390502',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008FP',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008FP',
                'hp_keyboard_serial' => 'BKTCF0CCPKPNON',
                'hp_mouse_serial' => 'FKTFR0AJPKP07G',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '2-AM-DSLR-AK',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0003-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Barshitakli, Tehsil Office Premises, Barshitakli 444401',
                'district' => 'Akola',
                'tahsil' => 'Barshitakli',
                'pin_code' => '444401',
                'receiver_name' => 'Ms. Alka Purad',
                'contact_no' => '9552454150',
                'dc_ir_no' => '003',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390503',
                'representative_name' => null,
                'aio_hp_serial' => '1N152007XZ',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152007XZ',
                'hp_keyboard_serial' => 'BKTCF0CCPKP0ET',
                'hp_mouse_serial' => 'FKTFR0AJPKPNOS',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '3-AM-SDSLR-BR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0004-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Balapur, Khamgaon Road, Near Government Hospital, Balapur 444302',
                'district' => 'Akola',
                'tahsil' => 'Balapur',
                'pin_code' => '444302',
                'receiver_name' => 'Mr. Pravin Pandey',
                'contact_no' => '7030118859',
                'dc_ir_no' => '004',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390504',
                'representative_name' => null,
                'aio_hp_serial' => '1N1520085N',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N1520085N',
                'hp_keyboard_serial' => 'BKTCF0CCPKP08L',
                'hp_mouse_serial' => 'FKTFR0AJPKPM5E',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '4-AM-SDSLR-BLR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0005-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Telhara, Gadegaon, Tehsil Office Premises, Telhara 444108',
                'district' => 'Akola',
                'tahsil' => 'Telhara',
                'pin_code' => '444108',
                'receiver_name' => 'Ms. Leena Kharode',
                'contact_no' => '9665564585',
                'dc_ir_no' => '005',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390505',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008JW',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008JW',
                'hp_keyboard_serial' => 'BKTCF0CCPKP0C2',
                'hp_mouse_serial' => 'FKTFR0AJPKPMVA',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '5-AM-SDSLR-TLR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0006-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Murtizapur, Collector Office Complex, Murtizapur 444107',
                'district' => 'Akola',
                'tahsil' => 'Murtizapur',
                'pin_code' => '444107',
                'receiver_name' => 'Mr. Rajesh Gawande',
                'contact_no' => '9421829182',
                'dc_ir_no' => '006',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390506',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008H5',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008H5',
                'hp_keyboard_serial' => 'BKTCF0CCPKPNY1',
                'hp_mouse_serial' => 'FKTFR0AJPKPMKV',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '6-AM-SDSLR-MR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0007-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Patur, Tehsil Office Premises, Patur 444501',
                'district' => 'Akola',
                'tahsil' => 'Patur',
                'pin_code' => '444501',
                'receiver_name' => 'Ms. Bharti Raut',
                'contact_no' => '9420856720',
                'dc_ir_no' => '007',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390507',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008HQ',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008HQ',
                'hp_keyboard_serial' => 'BKTCF0CCPKPNP8',
                'hp_mouse_serial' => 'FKTFR0AJPKPN21',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '7-AM-SDSLR-PTR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0008-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Akot, Tehsil Office Premises, Akot 444101',
                'district' => 'Akola',
                'tahsil' => 'Akot',
                'pin_code' => '444101',
                'receiver_name' => 'Mr. Deepak Patil',
                'contact_no' => '9765432180',
                'dc_ir_no' => '008',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390508',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008JK',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008JK',
                'hp_keyboard_serial' => 'BKTCF0CCPKPN85',
                'hp_mouse_serial' => 'FKTFR0AJPKPMZ7',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '8-AM-SDSLR-AKT',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0009-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Circle Superintendent, Land Records, Washim, Collector Office Complex, Washim 444505',
                'district' => 'Washim',
                'tahsil' => 'Washim',
                'pin_code' => '444505',
                'receiver_name' => 'Ms. Priya Sharma',
                'contact_no' => '9876543210',
                'dc_ir_no' => '009',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390509',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008LM',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008LM',
                'hp_keyboard_serial' => 'BKTCF0CCPKPOP2',
                'hp_mouse_serial' => 'FKTFR0AJPKPQW3',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '9-AM-CSLR-WSM',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0010-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Karanja, Tehsil Office Premises, Karanja 444106',
                'district' => 'Washim',
                'tahsil' => 'Karanja',
                'pin_code' => '444106',
                'receiver_name' => 'Mr. Suresh Deshmukh',
                'contact_no' => '9123456789',
                'dc_ir_no' => '010',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390510',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008NP',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => false,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008NP',
                'hp_keyboard_serial' => 'BKTCF0CCPKPRT4',
                'hp_mouse_serial' => 'FKTFR0AJPKPUV5',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '10-AM-SDSLR-KRJ',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
    }


    /**
     * Get the second batch of data for testing.
     *
     * @return array
     */
    private function getDataBatch2()
    {
        return [
            [
                'sr_no' => 'DC-0011-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Malegaon, Tehsil Office Premises, Malegaon 444503',
                'district' => 'Washim',
                'tahsil' => 'Malegaon',
                'pin_code' => '444503',
                'receiver_name' => 'Ms. Kavita Jadhav',
                'contact_no' => '9234567890',
                'dc_ir_no' => '011',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390511',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008QR',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008QR',
                'hp_keyboard_serial' => 'BKTCF0CCPKPST6',
                'hp_mouse_serial' => 'FKTFR0AJPKPWX7',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '11-AM-SDSLR-MLG',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0012-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Risod, Tehsil Office Premises, Risod 444506',
                'district' => 'Washim',
                'tahsil' => 'Risod',
                'pin_code' => '444506',
                'receiver_name' => 'Mr. Anil Kumar',
                'contact_no' => '9345678901',
                'dc_ir_no' => '012',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390512',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008TU',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008TU',
                'hp_keyboard_serial' => 'BKTCF0CCPKPYZ8',
                'hp_mouse_serial' => 'FKTFR0AJPKPAB9',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '12-AM-SDSLR-RSD',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0013-IN',
                'region_division' => 'Amravati',
                'location_address' => 'District Superintendent, Land Records, Yavatmal, Collector Office Complex, Yavatmal 445001',
                'district' => 'Yavatmal',
                'tahsil' => 'Yavatmal',
                'pin_code' => '445001',
                'receiver_name' => 'Mr. Rajesh Meshram',
                'contact_no' => '9456789012',
                'dc_ir_no' => '013',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390513',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008VW',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => false,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008VW',
                'hp_keyboard_serial' => 'BKTCF0CCPKPCD0',
                'hp_mouse_serial' => 'FKTFR0AJPKPEF1',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '13-AM-DSLR-YTL',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'High',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0014-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Arni, Tehsil Office Premises, Arni 445103',
                'district' => 'Yavatmal',
                'tahsil' => 'Arni',
                'pin_code' => '445103',
                'receiver_name' => 'Ms. Sunita Gaikwad',
                'contact_no' => '9567890123',
                'dc_ir_no' => '014',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390514',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008XY',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008XY',
                'hp_keyboard_serial' => 'BKTCF0CCPKPGH2',
                'hp_mouse_serial' => 'FKTFR0AJPKPIJ3',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '14-AM-SDSLR-ARN',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0015-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Babhulgaon, Tehsil Office Premises, Babhulgaon 445104',
                'district' => 'Yavatmal',
                'tahsil' => 'Babhulgaon',
                'pin_code' => '445104',
                'receiver_name' => 'Mr. Vikas Thakre',
                'contact_no' => '9678901234',
                'dc_ir_no' => '015',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390515',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008ZA',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'In Transit',
                'installation_status' => 'Pending',
                'soft_copy_dc' => false,
                'soft_copy_ir' => false,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008ZA',
                'hp_keyboard_serial' => 'BKTCF0CCPKPKL4',
                'hp_mouse_serial' => 'FKTFR0AJPKPMN5',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '15-AM-SDSLR-BBG',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Low',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0016-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Darwha, Tehsil Office Premises, Darwha 445202',
                'district' => 'Yavatmal',
                'tahsil' => 'Darwha',
                'pin_code' => '445202',
                'receiver_name' => 'Ms. Meera Patil',
                'contact_no' => '9789012345',
                'dc_ir_no' => '016',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390516',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008BC',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008BC',
                'hp_keyboard_serial' => 'BKTCF0CCPKPOP6',
                'hp_mouse_serial' => 'FKTFR0AJPKPQR7',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '16-AM-SDSLR-DRW',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0017-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Digras, Tehsil Office Premises, Digras 445203',
                'district' => 'Yavatmal',
                'tahsil' => 'Digras',
                'pin_code' => '445203',
                'receiver_name' => 'Mr. Santosh Kale',
                'contact_no' => '9890123456',
                'dc_ir_no' => '017',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390517',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008DE',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008DE',
                'hp_keyboard_serial' => 'BKTCF0CCPKPST8',
                'hp_mouse_serial' => 'FKTFR0AJPKPUV9',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '17-AM-SDSLR-DGR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0018-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Ghatanji, Tehsil Office Premises, Ghatanji 445301',
                'district' => 'Yavatmal',
                'tahsil' => 'Ghatanji',
                'pin_code' => '445301',
                'receiver_name' => 'Ms. Priyanka Bhoyar',
                'contact_no' => '9901234567',
                'dc_ir_no' => '018',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390518',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008FG',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => false,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008FG',
                'hp_keyboard_serial' => 'BKTCF0CCPKPWX0',
                'hp_mouse_serial' => 'FKTFR0AJPKPYZ1',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '18-AM-SDSLR-GTJ',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'High',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0019-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Kalamb, Tehsil Office Premises, Kalamb 445401',
                'district' => 'Yavatmal',
                'tahsil' => 'Kalamb',
                'pin_code' => '445401',
                'receiver_name' => 'Mr. Ramesh Dongre',
                'contact_no' => '9012345678',
                'dc_ir_no' => '019',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390519',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008HI',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008HI',
                'hp_keyboard_serial' => 'BKTCF0CCPKPAB2',
                'hp_mouse_serial' => 'FKTFR0AJPKPCD3',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '19-AM-SDSLR-KLB',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0020-IN',
                'region_division' => 'Amravati',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Kelapur, Tehsil Office Premises, Kelapur 445402',
                'district' => 'Yavatmal',
                'tahsil' => 'Kelapur',
                'pin_code' => '445402',
                'receiver_name' => 'Ms. Vandana Shinde',
                'contact_no' => '9123456789',
                'dc_ir_no' => '020',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390520',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008JK',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'In Transit',
                'installation_status' => 'Pending',
                'soft_copy_dc' => false,
                'soft_copy_ir' => false,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008JK',
                'hp_keyboard_serial' => 'BKTCF0CCPKPEF4',
                'hp_mouse_serial' => 'FKTFR0AJPKPGH5',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '20-AM-SDSLR-KLP',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Low',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
    }

    private function getDataBatch3()
    {
        return [
            [
                'sr_no' => 'DC-0021-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Deputy Director, Land Records, Nagpur Region, Central Avenue, Civil Lines, Nagpur 440001',
                'district' => 'Nagpur',
                'tahsil' => 'Nagpur',
                'pin_code' => '440001',
                'receiver_name' => 'Mr. Amol Deshmukh',
                'contact_no' => '9234567890',
                'dc_ir_no' => '021',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390521',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008LM',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => true,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008LM',
                'hp_keyboard_serial' => 'BKTCF0CCPKPIJ6',
                'hp_mouse_serial' => 'FKTFR0AJPKPKL7',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '21-NG-DDLR',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'High',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0022-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'District Superintendent, Land Records, Wardha, Collector Office Complex, Wardha 442001',
                'district' => 'Wardha',
                'tahsil' => 'Wardha',
                'pin_code' => '442001',
                'receiver_name' => 'Ms. Pooja Rathod',
                'contact_no' => '9345678901',
                'dc_ir_no' => '022',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390522',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008NO',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008NO',
                'hp_keyboard_serial' => 'BKTCF0CCPKPMN8',
                'hp_mouse_serial' => 'FKTFR0AJPKPOP9',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '22-NG-DSLR-WRD',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0023-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Arvi, Tehsil Office Premises, Arvi 442201',
                'district' => 'Wardha',
                'tahsil' => 'Arvi',
                'pin_code' => '442201',
                'receiver_name' => 'Mr. Ganesh Bhosale',
                'contact_no' => '9456789012',
                'dc_ir_no' => '023',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390523',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008PQ',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008PQ',
                'hp_keyboard_serial' => 'BKTCF0CCPKPQR0',
                'hp_mouse_serial' => 'FKTFR0AJPKPST1',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '23-NG-SDSLR-ARV',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0024-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Deoli, Tehsil Office Premises, Deoli 442102',
                'district' => 'Wardha',
                'tahsil' => 'Deoli',
                'pin_code' => '442102',
                'receiver_name' => 'Ms. Sneha Waghmare',
                'contact_no' => '9567890123',
                'dc_ir_no' => '024',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390524',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008RS',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => false,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008RS',
                'hp_keyboard_serial' => 'BKTCF0CCPKPUV2',
                'hp_mouse_serial' => 'FKTFR0AJPKPWX3',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '24-NG-SDSLR-DEO',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'High',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0025-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Hinganghat, Tehsil Office Premises, Hinganghat 442301',
                'district' => 'Wardha',
                'tahsil' => 'Hinganghat',
                'pin_code' => '442301',
                'receiver_name' => 'Mr. Prakash Alone',
                'contact_no' => '9678901234',
                'dc_ir_no' => '025',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390525',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008TU',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'In Transit',
                'installation_status' => 'Pending',
                'soft_copy_dc' => false,
                'soft_copy_ir' => false,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008TU',
                'hp_keyboard_serial' => 'BKTCF0CCPKPYZ4',
                'hp_mouse_serial' => 'FKTFR0AJPKPAB5',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '25-NG-SDSLR-HNG',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Low',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0026-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Samudrapur, Tehsil Office Premises, Samudrapur 442302',
                'district' => 'Wardha',
                'tahsil' => 'Samudrapur',
                'pin_code' => '442302',
                'receiver_name' => 'Ms. Archana Bhagat',
                'contact_no' => '9789012345',
                'dc_ir_no' => '026',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390526',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008VW',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => true,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008VW',
                'hp_keyboard_serial' => 'BKTCF0CCPKPCD6',
                'hp_mouse_serial' => 'FKTFR0AJPKPEF7',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '26-NG-SDSLR-SMD',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0027-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Seloo, Tehsil Office Premises, Seloo 442104',
                'district' => 'Wardha',
                'tahsil' => 'Seloo',
                'pin_code' => '442104',
                'receiver_name' => 'Mr. Mahesh Kumbhare',
                'contact_no' => '9890123456',
                'dc_ir_no' => '027',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390527',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008XY',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => false,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008XY',
                'hp_keyboard_serial' => 'BKTCF0CCPKPGH8',
                'hp_mouse_serial' => 'FKTFR0AJPKPIJ9',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '27-NG-SDSLR-SEL',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0028-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'District Superintendent, Land Records, Chandrapur, Collector Office Complex, Chandrapur 442401',
                'district' => 'Chandrapur',
                'tahsil' => 'Chandrapur',
                'pin_code' => '442401',
                'receiver_name' => 'Ms. Rashmi Deshpande',
                'contact_no' => '9901234567',
                'dc_ir_no' => '028',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390528',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008ZA',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => false,
                'original_pod_received' => false,
                'original_dc_received' => false,
                'ir_original_copy_received' => true,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008ZA',
                'hp_keyboard_serial' => 'BKTCF0CCPKPKL0',
                'hp_mouse_serial' => 'FKTFR0AJPKPMN1',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '28-NG-DSLR-CHD',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'High',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0029-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Ballarpur, Tehsil Office Premises, Ballarpur 442701',
                'district' => 'Chandrapur',
                'tahsil' => 'Ballarpur',
                'pin_code' => '442701',
                'receiver_name' => 'Mr. Sunil Gajbhiye',
                'contact_no' => '9012345678',
                'dc_ir_no' => '029',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390529',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008BC',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'Delivered',
                'installation_status' => 'Installed',
                'soft_copy_dc' => true,
                'soft_copy_ir' => true,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => true,
                'os_installation_photo_taken' => true,
                'belarc_report_generated' => true,
                'hp_440_g9_serial' => '1N152008BC',
                'hp_keyboard_serial' => 'BKTCF0CCPKPOP2',
                'hp_mouse_serial' => 'FKTFR0AJPKPQR3',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '29-NG-SDSLR-BLP',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Medium',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'sr_no' => 'DC-0030-IN',
                'region_division' => 'Nagpur',
                'location_address' => 'Sub-Divisional Superintendent, Land Records, Brahmapuri, Tehsil Office Premises, Brahmapuri 441206',
                'district' => 'Chandrapur',
                'tahsil' => 'Brahmapuri',
                'pin_code' => '441206',
                'receiver_name' => 'Ms. Nutan Wankhede',
                'contact_no' => '9123456789',
                'dc_ir_no' => '030',
                'dispatch_date' => null,
                'delivery_date' => null,
                'installation_date' => null,
                'total_boxes' => null,
                'courier_docket_no' => '81390530',
                'representative_name' => null,
                'aio_hp_serial' => '1N152008DE',
                'keyboard_serial' => null,
                'mouse_serial' => null,
                'ups_serial' => null,
                'antivirus' => null,
                'breakage_notes' => null,
                'ir_receiver_name' => null,
                'ir_receiver_designation' => null,
                'entity_vendor_name' => null,
                'vendor_contact_number' => null,
                'charges' => null,
                'remarks' => null,
                'delivery_status' => 'In Transit',
                'installation_status' => null,
                'soft_copy_dc' => false,
                'soft_copy_ir' => false,
                'original_pod_received' => null,
                'original_dc_received' => false,
                'ir_original_copy_received' => false,
                'back_side_photo_taken' => false,
                'os_installation_photo_taken' => false,
                'belarc_report_generated' => false,
                'hp_440_g9_serial' => '1N152008DE',
                'hp_keyboard_serial' => 'BKTCF0CCPKPST4',
                'hp_mouse_serial' => 'FKTFR0AJPKPUV5',
                'updated_antivirus' => null,
                'updated_breakage_notes' => null,
                'updated_ir_receiver_name' => null,
                'updated_ir_receiver_designation' => null,
                'updated_installation_date' => null,
                'updated_remarks' => null,
                'hostname' => '30-NG-SDSLR-BRM',
                'updated_entity_vendor' => null,
                'updated_contact_number' => null,
                'delivery_report_file' => null,
                'installation_report_file' => null,
                'belarc_report_file' => null,
                'back_side_photo_file' => null,
                'os_installation_photo_file' => null,
                'keyboard_photo_file' => null,
                'mouse_photo_file' => null,
                'screenshot_file' => null,
                'evidence_file' => null,
                'additional_documents' => null,
                'priority' => 'Low',
                'assigned_technician' => null,
                'internal_notes' => null,
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
    }
    
    private function getDataBatch4()
    {
        return [];
    }
    private function getDataBatch5()
    {
        return [];
    }
    private function getDataBatch6()
    {
        return [];
    }
    private function getDataBatch7()
    {
        return [];
    }
    private function getDataBatch8()
    {
        return [];
    }
    private function getDataBatch9()
    {
        return [];
    }
    private function getDataBatch10()
    {
        return [];
    }

    /**
     * Handle NOT NULL constraints by providing default values
     */
    private function handleNotNullConstraints($installation)
    {
        // Fields that might have NOT NULL constraints but we're setting to null
        $defaultValues = [
            'original_pod_received' => false,  // Default to false instead of null
            'installation_status' => 'Pending', // Default status for null values
            'delivery_status' => $installation['delivery_status'] ?? 'Pending',
            'soft_copy_dc' => $installation['soft_copy_dc'] ?? false,
            'soft_copy_ir' => $installation['soft_copy_ir'] ?? false,
            'original_dc_received' => $installation['original_dc_received'] ?? false,
            'ir_original_copy_received' => $installation['ir_original_copy_received'] ?? false,
            'back_side_photo_taken' => $installation['back_side_photo_taken'] ?? false,
            'os_installation_photo_taken' => $installation['os_installation_photo_taken'] ?? false,
            'belarc_report_generated' => $installation['belarc_report_generated'] ?? false,
            'is_active' => $installation['is_active'] ?? true,
            'priority' => $installation['priority'] ?? 'Medium',
            'created_by' => $installation['created_by'] ?? 1,
            'updated_by' => $installation['updated_by'] ?? 1,
        ];

        // Override null values with defaults
        foreach ($defaultValues as $field => $defaultValue) {
            if ($installation[$field] === null) {
                $installation[$field] = $defaultValue;
            }
        }

        return $installation;
    }

    /**
     * Helper method to convert boolean strings to boolean values
     */
    private function convertBoolean($value)
    {
        if ($value === 'Yes') return true;
        if ($value === 'No') return false;
        return null;
    }

    /**
     * Helper method to clean and format contact numbers
     */
    private function formatContactNumber($contact)
    {
        if (!$contact) return null;
        return (string) $contact;
    }

    /**
     * Helper method to format pin codes
     */
    private function formatPinCode($pinCode)
    {
        if (!$pinCode) return null;
        return str_replace(' ', '', (string) $pinCode);
    }

    /**
     * Disable foreign key checks in a database-agnostic way
     */
    private function disableForeignKeyChecks()
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                DB::statement('SET FOREIGN_KEY_CHECKS=0;');
                break;
            case 'sqlite':
                DB::statement('PRAGMA foreign_keys=OFF;');
                break;
            case 'pgsql':
                // PostgreSQL doesn't have a global way to disable foreign keys
                // We'll handle this differently if needed
                break;
        }
    }

    /**
     * Enable foreign key checks in a database-agnostic way
     */
    private function enableForeignKeyChecks()
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                DB::statement('SET FOREIGN_KEY_CHECKS=1;');
                break;
            case 'sqlite':
                DB::statement('PRAGMA foreign_keys=ON;');
                break;
            case 'pgsql':
                // PostgreSQL doesn't have a global way to disable foreign keys
                break;
        }
    }
}
